### ISSUE TITLE
Rename the plugin?

### ISSUE THREAD

**Issue by gcornut** [mattiaz9/gatsby-plugin-runtime-path-prefix#1]
Hello, thank you very much for this extension it's 100% what I needed and it works perfectly!

I would simply suggest renaming the plugin because it's actually a very generic plugin that can be used without IPFS or Swarm.  
For example, I will use it to deploy multiple versions of the same site under multiple path prefix (without having to rebuild them).

Maybe it could be renamed `gatsby-plugin-runtime-path-prefix`?

It could be easier for people to discover the plugin if was "marketed" as a plugin that can detect and update the `pathPrefix` at runtime.   
But of course IPFS and Swarm use cases should be mentioned.

**Comment by mattiaz9** [comment]
Thank you for your suggestion, I might as well do that.
