### ISSUE TITLE
Request for further path-prefixes e.g. btfs

### ISSUE THREAD

**Issue by parajbs** [mattiaz9/gatsby-plugin-runtime-path-prefix#8]
Hello **mattiaz9,**

Can you also integrate other path-prefixes from other decentralized storage platforms such as **btfs**.

I think for btfs it should be easy.

**For further platforms here is a small list:**
https://github.com/llaisdy/decentralized-storage/blob/master/README.org

I find the "gatsby-plugin-runtime-path-prefix" pugin very cool and helpful.
It would be even cooler if it continued to support networks.

I can search for other platforms, such as neofs or something.

**Comment by mattiaz9** [comment]
This is network agnostic.

You can setup a custom regex for that:
```js
module.exports = {
  pathPrefix: '__PATH_PREFIX__',
  plugins: [
    {
      resolve: `gatsby-plugin-runtime-path-prefix`,
      options: {
        prefix: `__PATH_PREFIX__`,
        pattern: /^(\/whateveryouwant\/[^/]+)/
      },
    },
  ],
};
```

**Comment by parajbs** [comment]
hi mattiaz9,

Yes, this is clear to me, but I only found the plugin because I entered ipfs in the search.

Therefore you should include a few platforms and also mention them in the readme, so that other developers who are looking for such a plugin can find it here.

For bfts it would be easy.

I think then this plugin could become one of the top plugins for "decentralized storage platforms" because it can also be used universally.

Was just an idea.
Thanks for this cool plugin.
